<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA | object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.5.3">
]
>

<object version="3.5.3" name="__root__" class="java.util.Vector">
   <object name="0" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">AIC</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="1" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">BAYES</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="2" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">BDeu</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="3" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">ENTROPY</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="4" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">MDL</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="5" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-mbc</object>
         <object name="8" class="java.lang.String">-S</object>
         <object name="9" class="java.lang.String">AIC</object>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="6" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-mbc</object>
         <object name="8" class="java.lang.String">-S</object>
         <object name="9" class="java.lang.String">BAYES</object>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="7" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-mbc</object>
         <object name="8" class="java.lang.String">-S</object>
         <object name="9" class="java.lang.String">BDeu</object>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="8" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-mbc</object>
         <object name="8" class="java.lang.String">-S</object>
         <object name="9" class="java.lang.String">ENTROPY</object>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="9" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-N</object>
         <object name="5" class="java.lang.String">-P</object>
         <object name="6" class="java.lang.String">1</object>
         <object name="7" class="java.lang.String">-mbc</object>
         <object name="8" class="java.lang.String">-S</object>
         <object name="9" class="java.lang.String">MDL</object>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="10" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-S</object>
         <object name="7" class="java.lang.String">AIC</object>
         <object name="8" class="java.lang.String"/>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="11" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-S</object>
         <object name="7" class="java.lang.String">BAYES</object>
         <object name="8" class="java.lang.String"/>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="12" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-S</object>
         <object name="7" class="java.lang.String">BDeu</object>
         <object name="8" class="java.lang.String"/>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="13" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-S</object>
         <object name="7" class="java.lang.String">ENTROPY</object>
         <object name="8" class="java.lang.String"/>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="14" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-S</object>
         <object name="7" class="java.lang.String">MDL</object>
         <object name="8" class="java.lang.String"/>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="15" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-mbc</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">AIC</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="16" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-mbc</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">BAYES</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="17" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">
         <object name="0" class="java.lang.String">-D</object>
         <object name="1" class="java.lang.String">-Q</object>
         <object name="2" class="java.lang.String">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object name="3" class="java.lang.String">--</object>
         <object name="4" class="java.lang.String">-P</object>
         <object name="5" class="java.lang.String">1</object>
         <object name="6" class="java.lang.String">-mbc</object>
         <object name="7" class="java.lang.String">-S</object>
         <object name="8" class="java.lang.String">BDeu</object>
         <object name="9" class="java.lang.String"/>
         <object name="10" class="java.lang.String"/>
         <object name="11" class="java.lang.String"/>
         <object name="12" class="java.lang.String"/>
         <object name="13" class="java.lang.String"/>
         <object name="14" class="java.lang.String">-E</object>
         <object name="15" class="java.lang.String">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object name="16" class="java.lang.String">--</object>
         <object name="17" class="java.lang.String">-A</object>
         <object name="18" class="java.lang.String">0.5</object>
         <object name="19" class="java.lang.String"/>
         <object name="20" class="java.lang.String"/>
         <object name="21" class="java.lang.String"/>
         <object name="22" class="java.lang.String"/>
      </object>
   </object>
   <object name="18" class="weka.classifiers.bayes.BayesNet">
      <object name="options" class="java.lang.String" array="yes">